export async function seed(knex) {
  await knex('questions').insert([
    {
      question_id: 1,
      quiz_id: 1,
      question_text: 'Pretend this is a longer question?',
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
      incorrect_answer2: 'incorrect answer2',
      incorrect_answer3: 'incorrect answer3',
    },
    {
      question_id: 2,
      quiz_id: 1,
      question_text: 'Another question could go here?',
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
    },
    {
      question_id: 3,
      quiz_id: 1,
      question_text: 'Asking very thoughtful questions?',
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
      incorrect_answer2: 'incorrect answer2',
      incorrect_answer3: 'incorrect answer3',
    },
    {
      question_id: 4,
      quiz_id: 2,
      question_text: 'Why do birds suddenly appear?',
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
      incorrect_answer2: 'incorrect answer2',
    },
    {
      question_id: 5,
      quiz_id: 2,
      question_text: 'How many roads must a man walk down?',
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
      incorrect_answer2: 'incorrect answer2',
      incorrect_answer3: 'incorrect answer3',
    },
    {
      question_id: 6,
      quiz_id: 3,
      question_text: "What's going on?",
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
    },
    {
      question_id: 7,
      quiz_id: 3,
      question_text: 'Why do you love me?',
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
      incorrect_answer2: 'incorrect answer2',
      incorrect_answer3: 'incorrect answer3',
    },
    {
      question_id: 8,
      quiz_id: 3,
      question_text: "What's the matter here?",
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
      incorrect_answer2: 'incorrect answer2',
      incorrect_answer3: 'incorrect answer3',
    },
  ])
}
