export async function seed(knex) {
  await knex('questions').insert([
    {
      question_id: 1,
      quiz_id: 1,
      question_text: 'What is my name?',
      correct_answer: 'rose',
      incorrect_answer1: 'harry',
      incorrect_answer2: 'norman',
      incorrect_answer3: 'gaby',
    },
    {
      question_id: 2,
      quiz_id: 1,
      question_text: 'What is my haircolour?',
      correct_answer: 'brown',
      incorrect_answer1: 'red',
    },
    {
      question_id: 3,
      quiz_id: 1,
      question_text: 'Which finger has a scar?',
      correct_answer: 'right pinky',
      incorrect_answer1: 'left thumb',
      incorrect_answer2: 'right middle finger',
      incorrect_answer3: 'right thumb',
    },
    {
      question_id: 4,
      quiz_id: 2,
      question_text: 'Why do birds suddenly appear?',
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
      incorrect_answer2: 'incorrect answer2',
    },
    {
      question_id: 5,
      quiz_id: 2,
      question_text: 'How many roads must a man walk down?',
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
      incorrect_answer2: 'incorrect answer2',
      incorrect_answer3: 'incorrect answer3',
    },
    {
      question_id: 6,
      quiz_id: 3,
      question_text: "What's going on?",
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
    },
    {
      question_id: 7,
      quiz_id: 3,
      question_text: 'Why do you love me?',
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
      incorrect_answer2: 'incorrect answer2',
      incorrect_answer3: 'incorrect answer3',
    },
    {
      question_id: 8,
      quiz_id: 3,
      question_text: "What's the matter here?",
      correct_answer: 'correct answer',
      incorrect_answer1: 'incorrect answer1',
      incorrect_answer2: 'incorrect answer2',
      incorrect_answer3: 'incorrect answer3',
    },
  ])
}
